[package]
name = "atrium-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
atrium-api = { version = "0.24.10", features = ["tokio", "bluesky", "agent"] }
bsky-sdk = "0.1.14"
dotenv = "0.15.0"
tokio = { version = "1.43",  features = ["macros", "rt-multi-thread"] }
